# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Default to triggering on all commits to all branches until the build works
#trigger:
#- 'master'

jobs:
- job: Build
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

- job: Test
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      npm test
    displayName: 'Run mocha tests'
